### PR TITLE
Add FieldsHelper

### PR DESCRIPTION
**Pull request by crystalenka**
This makes it work (at least nominally) in Joomla 4. :)

### CODE REVIEW

**Comment by degobbis** [comment]
Thank you for bringing this to my attention.

Unfortunately, this can't simply be adopted as it is, since no namespace mapping for the helper has been done in Joomla 3.10.x yet.

Can you please test my proposed change?
Does the plugin otherwise run without problems in Joomla 4?

```suggestion

if (version_compare(JVERSION, 4, 'lt'))
{
	\JLoader::registerNamespace('\\Joomla\\Component\\Fields\\Administrator\\Helper\\FieldsHelper', JPATH_ADMINISTRATOR . '/components/com_fields/helpers/fields.php');
}

use Joomla\Component\Fields\Administrator\Helper\FieldsHelper;
```

**Comment by crystalenka** [comment]
This change still works in Joomla 4.

It works for the most part in J4 but not with subform fields, even though it does show up in the field configuration. I'm not sure it's possible to show or hide subform fields conditionally? If it is, that would be amazing and solve some headaches for me. If not, that's fine too. :) Just would maybe add a note to the help text that it doesn't work in subforms.

**Comment by degobbis** [comment]
Thx for testing the Changes.

It works for the subform field itself, but not for the fields within it.

It seems that the showon functionality is rendered for these fields, but inside the subform field it is not taken into effect by the javascript.

Unfortunately, I have not been able to find a solution to this problem.

Something good it has anyway, with only a small adjustment it is compatible with J4 :-)

**Comment by crystalenka** [comment]
Thank you!!!

**Pull request closed without merging**
